name: Build and Push Docker Image

on:
    push:
        tags:
            - 'v*' # trigger only on v1.2.3 tags
jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get TAG name
              id: tag
              run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            #- name: Get TAG name
            #  id: meta
            #  uses: docker/metadata-action@v5
            #  with:
            #    images: pirraste/reimagined-disco-ui

            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: .docker/Dockerfile
                push: true
                tags: |
                  pirraste/reimagined-disco-ui:${{ steps.tag.outputs.TAG }}
                # pirraste/reimagined-disco-ui:latest
      
            - name: Install kustomize
              run: |
                curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.1/kustomize_v5.4.1_linux_amd64.tar.gz
                tar -xzf kustomize.tar.gz
                sudo mv kustomize /usr/local/bin/

            - name: Write back image tag in k8s repo
              env:
                GH_TOKEN: ${{ secrets.K8S_REPO_TOKEN }}
                IMAGE: pirraste/reimagined-disco-ui
                TAG: ${{ github.ref_name }}
              run: |
                git clone https://x-access-token:${GH_TOKEN}@github.com/pste/reimagined-disco-k8s.git k8s
                cd k8s
                kustomize edit set image ${IMAGE}:${TAG}
                git config user.email "actions@github.com"
                git config user.name "GitHub Actions"
                git add kustomization.yaml
                git commit -m "chore: update ${IMAGE} to ${TAG}"
                git push
